version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kingkong_db
    restart: always
    environment:
      POSTGRES_USER: saidaka
      POSTGRES_PASSWORD: Said
      POSTGRES_DB: kingkong_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  bot:
    build: .
    container_name: kingkong_bot
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://kingkong:strongpassword123@postgres:5432/kingkong_bot
    volumes:
      - ./downloads:/app/downloads
    command: ["sh", "-c", "/wait-for-it.sh postgres:5432 -- npm run start:prod"]

volumes:
  postgres_data:
